"""Abstract base class for trading strategies."""

import logging
from abc import ABC, abstractmethod
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


class Signal:
    """Represents a trading signal generated by a strategy."""

    def __init__(self, symbol: str, side: str, confidence: float,
                 reasoning: str, strategy_name: str,
                 metadata: Dict[str, Any] = None) -> None:
        self.symbol = symbol
        self.side = side  # "buy" or "sell"
        self.confidence = max(0.0, min(1.0, confidence))
        self.reasoning = reasoning
        self.strategy_name = strategy_name
        self.metadata = metadata or {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "symbol": self.symbol,
            "side": self.side,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "strategy_name": self.strategy_name,
            "metadata": self.metadata,
        }

    def __repr__(self) -> str:
        return (f"Signal({self.strategy_name}: {self.side} {self.symbol} "
                f"conf={self.confidence:.2f})")


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    def __init__(self, name: str) -> None:
        self.name = name

    @abstractmethod
    def analyze(self, market_data: Dict[str, Any]) -> List[Signal]:
        """Analyze market data and generate trading signals.

        Args:
            market_data: Dict containing candles, ticker, order_book, etc.
                Expected structure:
                {
                    "symbol": "BTC-USDT",
                    "exchange": "okx",
                    "candles": [{"timestamp", "open", "high", "low", "close", "volume"}, ...],
                    "ticker": {"symbol", "bid", "ask", "last", "volume", ...},
                    "order_book": {"bids": [...], "asks": [...]},
                }

        Returns:
            List of Signal objects.
        """
        ...

    def _validate_candles(self, candles: List[Dict[str, Any]],
                          min_count: int = 30) -> bool:
        """Check if we have enough candle data for analysis."""
        if not candles or len(candles) < min_count:
            logger.debug(
                "%s: insufficient candles (%d < %d)",
                self.name, len(candles) if candles else 0, min_count,
            )
            return False
        return True

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} name={self.name}>"